

--Users Table

CREATE TABLE Users(
	UserId INT IDENTITY(1,1) PRIMARY KEY,
	FullName NVARCHAR(100) NOT NULL,
	Email NVARCHAR(150) NOT NULL UNIQUE,
	PasswordHash NVARCHAR(255) NOT NULL,
	Role NVARCHAR(50) NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE()

);

-- Business Table

CREATE TABLE Businesses (
	BusinessId INT IDENTITY(1,1) PRIMARY KEY,
	BusinessName NVARCHAR(150) NOT NULL,
	Description NVARCHAR(500),
	Category NVARCHAR(100),
	OwnerUserId INT NOT NULL,
	Phone NVARCHAR(20),
	Email NVARCHAR(150),
	Address NVARCHAR(255),
	IsVerified BIT NOT NULL DEFAULT 0,
	CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_Businesses_Users
		FOREIGN KEY (OwnerUserId) REFERENCES Users(UserId)

);